# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20170523_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyuga',
            name='halfday_setting',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('F', 'Full')], default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='hyuga_requests',
            name='halfday_setting',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('F', 'Full')], default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='past_hyuga',
            name='halfday_setting',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('F', 'Full')], default='F', max_length=2),
        ),
    ]
