# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20170529_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyuga',
            name='halfday_setting',
            field=models.CharField(choices=[('F', 'Full'), ('M', 'Morning'), ('A', 'Afternoon')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='hyuga_requests',
            name='halfday_setting',
            field=models.CharField(choices=[('F', 'Full'), ('M', 'Morning'), ('A', 'Afternoon')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='past_hyuga',
            name='halfday_setting',
            field=models.CharField(choices=[('F', 'Full'), ('M', 'Morning'), ('A', 'Afternoon')], default='F', max_length=2),
        ),
    ]
