# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20170529_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
