# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20170529_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='used',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
