# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20170529_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyuga_Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(max_length=500)),
                ('username', models.CharField(default='', max_length=50)),
                ('halfday_setting', models.CharField(choices=[('F', 'Full'), ('M', 'Morning'), ('A', 'Afternoon')], default='F', max_length=2)),
            ],
        ),
    ]
