# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_hyuga_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hyuga',
            name='boss',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hyuga_confirmed',
            name='boss',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hyuga_requests',
            name='boss',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='past_hyuga',
            name='boss',
            field=models.CharField(default='', max_length=50),
        ),
    ]
