# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20170601_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hyuga',
            options={'verbose_name': 'Break List'},
        ),
    ]
