# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20170607_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hyuga',
            options={'verbose_name_plural': 'Break List'},
        ),
    ]
