# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20170607_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='boss',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='hyuga',
            old_name='boss',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='hyuga_confirmed',
            old_name='boss',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='hyuga_requests',
            old_name='boss',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='past_hyuga',
            old_name='boss',
            new_name='team',
        ),
    ]
